### ISSUE TITLE
Counter value of 999 should be allowed.

### ISSUE THREAD

**Issue by StryKaizer** [SetBased/php-rijksregisternummer#9]
In isValid counter is being tested to be between 1 and 998.

999 is also an allowed value (for male numbers), see https://nl.wikipedia.org/wiki/Rijksregisternummer

**Comment by prwater** [comment]
The official specifications in NL and FR both state the second group of numbers are in the range of 1 to 997 for men.

```
een tweede groep van drie cijfers, ter identificatie van de personen die op dezelfde dag geboren
zijn. Dit reeksnummer is paar voor een vrouw en onpaar voor een man. Het wordt in de volgorde
van de inschrijvingen toegekend, namelijk 001 tot 997 (man) en van 002 tot 998 (vrouw);
```
```
Il est attribué dans l'ordre des inscriptions ; il va de 001 à 997 pour un homme et de 002 à 998 pour une 
femme.
```

So, the information on Wikipedia is not correct.

See 
* https://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/instructies/IT-lijst/IT000_Rijksregisternummer.pdf
* https://www.ibz.rrn.fgov.be/fileadmin/user_upload/fr/rn/fichier-rn/fichier-RN.pdf

**Comment by StryKaizer** [comment]
Thanks, I updated wikipedia instead ;)

**Comment by prwater** [comment]
I see you have updated the erroneous example as well. Perfect!
